name: Build metrics

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish:
    name: generate repo metrics
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          template: repository
          filename: metrics.repository.svg
          user: garbles-labs
          repo: Solana.Unity-SDK
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1
