name: Build metrics

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish:
    name: generate repo metrics
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          template: repository
          base: ""
          committer_branch: gh-pages
          filename: metrics.repository.svg
          token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
          user: garbles-labs
          repo: Solana.Unity-SDK
          plugin_contributors: yes
          plugin_contributors_contributions: yes
